// ─────────────────────────────────────────────────────────────────
//  Globe — Auto-generated Events Data
//  Last updated: 2026-04-01 06:25 UTC
//  Source: Eventbrite · Designmynight · Time Out · Resident Advisor
//  DO NOT EDIT MANUALLY — this file is overwritten daily
// ─────────────────────────────────────────────────────────────────

const GLOBE_EVENTS = [
  {
    id: 1,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Kat Anderson",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Kat Anderson  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-kat-anderson",
    highlight: false,
    sponsored: false,
  },
  {
    id: 2,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Manuel Hernandez Rivera",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Manuel Hernandez Rivera  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-manuel-hernandez-rivera",
    highlight: false,
    sponsored: false,
  },
  {
    id: 3,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Maya Silverberg",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Maya Silverberg  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-maya-silverberg",
    highlight: false,
    sponsored: false,
  },
  {
    id: 4,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "29 years later: Tracey Emin at the SLG",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  29 years later: Tracey Emin at the SLG  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/29-years-later-tracey-emin-at-the-slg",
    highlight: false,
    sponsored: false,
  },
  {
    id: 5,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Samantha Fellows",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Samantha Fellows  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-samantha-fellows",
    highlight: false,
    sponsored: false,
  },
  {
    id: 6,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Highlights from the Colecci\u00f3n Jumex, Mexico City",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Highlights from the Colecci\u00f3n Jumex, Mexico City  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/highlights-from-the-coleccion-jumex-mexico-city",
    highlight: false,
    sponsored: false,
  },
  {
    id: 7,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Meet South London Louie\u2019s Head Chef, Daniela Natale",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Meet South London Louie&#8217;s Head Chef, Daniela Natale  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/meet-south-london-louies-head-chef-daniela-natale",
    highlight: false,
    sponsored: false,
  },
  {
    id: 8,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Holiday Gift Ideas from the SLG Bookshop",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Holiday Gift Ideas from the SLG Bookshop  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/holiday-gift-ideas-from-the-slg-bookshop-2",
    highlight: false,
    sponsored: false,
  },
  {
    id: 9,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "The SLG announces its upcoming programme for 2026",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  The SLG announces its upcoming programme for 2026  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/2026-exhibitions",
    highlight: false,
    sponsored: false,
  },
  {
    id: 10,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Who was the forgotten artist and theorist Emily Noyes Vanderpoel?",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Who was the forgotten artist and theorist Emily Noyes Vanderpoel?  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/who-was-the-forgotten-artist-and-theorist-emily-noyes-vanderpoel",
    highlight: false,
    sponsored: false,
  },
  {
    id: 11,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY ANNOUNCES GARDEN WITH KINETIC ARTIST LUCY GREGORY, GARDEN DESIGNER NAOMI FERRETT-COHEN, AND SUPPORTER ING AT RHS CHELSEA FLOWER SHOW 2026",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "London, UK; March 2026 \u2014 Saatchi Gallery is to present its garden at the RHS Chelsea Flower Show 2026 in collaboration with kinetic artist Lucy Gregory, garden designer Naomi Ferrett-Cohen, and supporter ING. Created for Saatchi Gallery\u2019s sixth collaboration with the internationally acclaimed RHS Ch",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-announces-garden-with-kinetic-artist-lucy-gregory-garden-designer-naomi-ferrett-cohen-and-supporter-ing-at-rhs-chelsea-flower-show-2026?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-announces-garden-with-kinetic-artist-lucy-gregory-garden-designer-naomi-ferrett-cohen-and-supporter-ing-at-rhs-chelsea-flower-show-2026",
    highlight: false,
    sponsored: false,
  },
  {
    id: 12,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS FIRST GROUP TEXTILE ART EXHIBITION, TEXTILE ART REDEFINED",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Textile Art Redefined explores the innovation and creativity of contemporary fine art textiles. Showcasing work by more than 15 visionary artists, the exhibition both celebrates the vibrancy of textile art today and expands the very definition. \n The post  SAATCHI GALLERY PRESENTS FIRST GROUP TEXTIL",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-first-group-textile-art-exhibition-textile-art-redefined?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-first-group-textile-art-exhibition-textile-art-redefined",
    highlight: false,
    sponsored: false,
  },
  {
    id: 13,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS CAROLINE WONG: GIRLS WHO DEVOUR",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "This exhibition brings together interconnected bodies of work by London-based British-Malaysian-Chinese artist Caroline Wong. Across pastel drawings and mixed-media paintings, Wong explores femininity, appetite, desire, and excess through scenes of convivial consumption and intimate female gathering",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-caroline-wong-girls-who-devour?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-caroline-wong-girls-who-devour",
    highlight: false,
    sponsored: false,
  },
  {
    id: 14,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS ANNA LIBER LEWIS: SPECTRAL INTERFERENCE",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Gesture and Being brings together new work from six recent graduates of Royal College of Art and the Slade School of Fine Art: Anna Curzon Price, Gala Hills, Katja Farin, Mia Wilkinson, Poppy Critchlow and Qian Zhong. \n The post  SAATCHI GALLERY PRESENTS ANNA LIBER LEWIS: SPECTRAL INTERFERENCE  firs",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-spectral-interference?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-spectral-interference",
    highlight: false,
    sponsored: false,
  },
  {
    id: 15,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS NEW GRADUATE EXHIBITION, GESTURE & BEING",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Gesture and Being brings together new work from six recent graduates of Royal College of Art and the Slade School of Fine Art: Anna Curzon Price, Gala Hills, Katja Farin, Mia Wilkinson, Poppy Critchlow and Qian Zhong. \n The post  SAATCHI GALLERY PRESENTS NEW GRADUATE EXHIBITION, GESTURE & BEING  fir",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-graduate-exhibition-gesture-being?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-graduate-exhibition-gesture-being",
    highlight: false,
    sponsored: false,
  },
  {
    id: 16,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS GOOD EYE PROJECTS 2026",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Good Eye Projects returns to Saatchi Gallery with a group exhibition of artists from their Autumn 2024, Spring 2025, and Summer 2025 residency iterations. \n The post  SAATCHI GALLERY PRESENTS GOOD EYE PROJECTS 2026  first appeared on  Saatchi Gallery .",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-good-eye-projects-2026?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-good-eye-projects-2026",
    highlight: false,
    sponsored: false,
  },
  {
    id: 17,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "PEUGEOT AND SAATCHI GALLERY ANNOUNCE WINNER OF THE FIRST ARTIST OF THE FUTURE PRIZE 2025",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "PEUGEOT, in collaboration with Saatchi Gallery, is delighted to announce DYSPLA as the overall winner of the inaugural Artist of the Future Prize 2025 \u2013 a new award celebrating innovation in digital art across the UK and Europe. \n The post  PEUGEOT AND SAATCHI GALLERY ANNOUNCE WINNER OF THE FIRST AR",
    url: "https://www.saatchigallery.com/press/release/peugeot-and-saatchi-gallery-announce-winner-of-the-first-artist-of-the-future-prize-2025?utm_source=rss&utm_medium=rss&utm_campaign=peugeot-and-saatchi-gallery-announce-winner-of-the-first-artist-of-the-future-prize-2025",
    highlight: false,
    sponsored: false,
  },
  {
    id: 18,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "PEUGEOT AND SAATCHI GALLERY ANNOUNCE FINALISTS FOR THE FIRST ARTIST OF THE FUTURE PRIZE 2025",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "PEUGEOT, in collaboration with Saatchi Gallery, is pleased to announce the ten finalists shortlisted for the inaugural Artist of the Future Prize 2025 \u2013 a new award celebrating innovation in digital art across the UK and Europe. \n The post  PEUGEOT AND SAATCHI GALLERY ANNOUNCE FINALISTS FOR THE FIRS",
    url: "https://www.saatchigallery.com/press/release/peugeot-and-saatchi-gallery-announce-finalists-for-the-first-artist-of-the-future-prize-2025?utm_source=rss&utm_medium=rss&utm_campaign=peugeot-and-saatchi-gallery-announce-finalists-for-the-first-artist-of-the-future-prize-2025",
    highlight: false,
    sponsored: false,
  },
  {
    id: 19,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "Vogue Ukraine presents FUTURESPECTIVE, an exhibition of contemporary Ukrainian photography at the Saatchi Gallery in London",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "FUTURESPECTIVE is an initiative by Vogue Ukraine in partnership with PhotoVogue, aimed to support and promote Ukrainian photographers on the international scene. The debut exhibition features works by 34 talents across genres and formats \u2014 from documentary and fine-art photography to still life, lan",
    url: "https://www.saatchigallery.com/press/release/vogue-ukraine-presents-futurespective-an-exhibition-of-contemporary-ukrainian-photography-at-the-saatchi-gallery-in-london?utm_source=rss&utm_medium=rss&utm_campaign=vogue-ukraine-presents-futurespective-an-exhibition-of-contemporary-ukrainian-photography-at-the-saatchi-gallery-in-london",
    highlight: false,
    sponsored: false,
  },
  {
    id: 20,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY & THE V&A PRESENT THE SECOND EDITION OF ACCLAIMED DUTCH FEMALE ARTISTS EXHIBITION, STANDING ON THE SHOULDERS OF GIANTS II: A UNIQUE DIALOGUE BETWEEN PAST AND PRESENT",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "From 22 November 2025, Saatchi Gallery will present the highly anticipated second edition of Standing on the Shoulders of Giants, featuring 10 contemporary Dutch female artists in collaboration with the V&#038;A. \n The post  SAATCHI GALLERY & THE V&A PRESENT THE SECOND EDITION OF ACCLAIMED DUTCH FEM",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-the-va-present-the-second-edition-of-acclaimed-dutch-female-artists-exhibition-standing-on-the-shoulders-of-giants-ii-a-unique-dialogue-between-past-and-present?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-the-va-present-the-second-edition-of-acclaimed-dutch-female-artists-exhibition-standing-on-the-shoulders-of-giants-ii-a-unique-dialogue-between-past-and-present",
    highlight: false,
    sponsored: false,
  }
];

// ── TYPE CONFIG: colours, icons, labels ──
const EVENT_TYPES = {
  gallery:     { color: "#C8102E", icon: "🏛️", label: "Gallery Opening", markerColor: "#C8102E" },
  exhibition:  { color: "#D4A020", icon: "🖼️", label: "Exhibition",      markerColor: "#D4A020" },
  popup:       { color: "#1C6B3A", icon: "🛍️", label: "Pop-up & Market", markerColor: "#1C6B3A" },
  performance: { color: "#6B3FA0", icon: "🎭", label: "Performance",     markerColor: "#6B3FA0" },
  talk:        { color: "#2A5BAD", icon: "🎙️", label: "Artist Talk",     markerColor: "#2A5BAD" },
};
