// ─────────────────────────────────────────────────────────────────
//  Globe — Auto-generated Events Data
//  Last updated: 2026-02-24 05:56 UTC
//  Source: Eventbrite · Designmynight · Time Out · Resident Advisor
//  DO NOT EDIT MANUALLY — this file is overwritten daily
// ─────────────────────────────────────────────────────────────────

const GLOBE_EVENTS = [
  {
    id: 1,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Highlights from the Colecci\u00f3n Jumex, Mexico City",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Highlights from the Colecci\u00f3n Jumex, Mexico City  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/highlights-from-the-coleccion-jumex-mexico-city",
    highlight: false,
    sponsored: false,
  },
  {
    id: 2,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Meet South London Louie\u2019s Head Chef, Daniela Natale",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Meet South London Louie&#8217;s Head Chef, Daniela Natale  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/meet-south-london-louies-head-chef-daniela-natale",
    highlight: false,
    sponsored: false,
  },
  {
    id: 3,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Holiday Gift Ideas from the SLG Bookshop",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Holiday Gift Ideas from the SLG Bookshop  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/holiday-gift-ideas-from-the-slg-bookshop-2",
    highlight: false,
    sponsored: false,
  },
  {
    id: 4,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "The SLG announces its upcoming programme for 2026",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  The SLG announces its upcoming programme for 2026  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/2026-exhibitions",
    highlight: false,
    sponsored: false,
  },
  {
    id: 5,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Who was the forgotten artist and theorist Emily Noyes Vanderpoel?",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Who was the forgotten artist and theorist Emily Noyes Vanderpoel?  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/who-was-the-forgotten-artist-and-theorist-emily-noyes-vanderpoel",
    highlight: false,
    sponsored: false,
  },
  {
    id: 6,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "SLG returns to Frieze London 2025",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  SLG returns to Frieze London 2025  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/slg-returns-to-frieze-london-2025",
    highlight: false,
    sponsored: false,
  },
  {
    id: 7,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Appau Jnr Boakye-Yiadom",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Appau Jnr Boakye-Yiadom  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-appau-jnr-boakye-yiadom",
    highlight: false,
    sponsored: false,
  },
  {
    id: 8,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "5 things to know about artist Leonardo Drew",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  5 things to know about artist Leonardo Drew  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/5-things-to-know-about-artist-leonardo-drew",
    highlight: false,
    sponsored: false,
  },
  {
    id: 9,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "5 Ways We\u2019re Making Our Work More Sustainable at the SLG",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  5 Ways We\u2019re Making Our Work More Sustainable at the SLG  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/sustainability",
    highlight: false,
    sponsored: false,
  },
  {
    id: 10,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "5 Things to Spot in Christina Kimeze: Between Wood and Wheel",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  5 Things to Spot in Christina Kimeze: Between Wood and Wheel  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/5-things-to-spot-in-christina-kimeze-between-wood-and-wheel",
    highlight: false,
    sponsored: false,
  },
  {
    id: 11,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS ANNA LIBER LEWIS: SPECTRAL INTERFERENCE",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Gesture and Being brings together new work from six recent graduates of Royal College of Art and the Slade School of Fine Art: Anna Curzon Price, Gala Hills, Katja Farin, Mia Wilkinson, Poppy Critchlow and Qian Zhong. \n The post  SAATCHI GALLERY PRESENTS ANNA LIBER LEWIS: SPECTRAL INTERFERENCE  firs",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-spectral-interference?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-spectral-interference",
    highlight: false,
    sponsored: false,
  },
  {
    id: 12,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS NEW GRADUATE EXHIBITION, GESTURE & BEING",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Gesture and Being brings together new work from six recent graduates of Royal College of Art and the Slade School of Fine Art: Anna Curzon Price, Gala Hills, Katja Farin, Mia Wilkinson, Poppy Critchlow and Qian Zhong. \n The post  SAATCHI GALLERY PRESENTS NEW GRADUATE EXHIBITION, GESTURE & BEING  fir",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-graduate-exhibition-gesture-being?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-graduate-exhibition-gesture-being",
    highlight: false,
    sponsored: false,
  },
  {
    id: 13,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY PRESENTS GOOD EYE PROJECTS 2026",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Good Eye Projects returns to Saatchi Gallery with a group exhibition of artists from their Autumn 2024, Spring 2025, and Summer 2025 residency iterations. \n The post  SAATCHI GALLERY PRESENTS GOOD EYE PROJECTS 2026  first appeared on  Saatchi Gallery .",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-good-eye-projects-2026?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-good-eye-projects-2026",
    highlight: false,
    sponsored: false,
  },
  {
    id: 14,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "PEUGEOT AND SAATCHI GALLERY ANNOUNCE WINNER OF THE FIRST ARTIST OF THE FUTURE PRIZE 2025",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "PEUGEOT, in collaboration with Saatchi Gallery, is delighted to announce DYSPLA as the overall winner of the inaugural Artist of the Future Prize 2025 \u2013 a new award celebrating innovation in digital art across the UK and Europe. \n The post  PEUGEOT AND SAATCHI GALLERY ANNOUNCE WINNER OF THE FIRST AR",
    url: "https://www.saatchigallery.com/press/release/peugeot-and-saatchi-gallery-announce-winner-of-the-first-artist-of-the-future-prize-2025?utm_source=rss&utm_medium=rss&utm_campaign=peugeot-and-saatchi-gallery-announce-winner-of-the-first-artist-of-the-future-prize-2025",
    highlight: false,
    sponsored: false,
  },
  {
    id: 15,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "PEUGEOT AND SAATCHI GALLERY ANNOUNCE FINALISTS FOR THE FIRST ARTIST OF THE FUTURE PRIZE 2025",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "PEUGEOT, in collaboration with Saatchi Gallery, is pleased to announce the ten finalists shortlisted for the inaugural Artist of the Future Prize 2025 \u2013 a new award celebrating innovation in digital art across the UK and Europe. \n The post  PEUGEOT AND SAATCHI GALLERY ANNOUNCE FINALISTS FOR THE FIRS",
    url: "https://www.saatchigallery.com/press/release/peugeot-and-saatchi-gallery-announce-finalists-for-the-first-artist-of-the-future-prize-2025?utm_source=rss&utm_medium=rss&utm_campaign=peugeot-and-saatchi-gallery-announce-finalists-for-the-first-artist-of-the-future-prize-2025",
    highlight: false,
    sponsored: false,
  },
  {
    id: 16,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "Vogue Ukraine presents FUTURESPECTIVE, an exhibition of contemporary Ukrainian photography at the Saatchi Gallery in London",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "FUTURESPECTIVE is an initiative by Vogue Ukraine in partnership with PhotoVogue, aimed to support and promote Ukrainian photographers on the international scene. The debut exhibition features works by 34 talents across genres and formats \u2014 from documentary and fine-art photography to still life, lan",
    url: "https://www.saatchigallery.com/press/release/vogue-ukraine-presents-futurespective-an-exhibition-of-contemporary-ukrainian-photography-at-the-saatchi-gallery-in-london?utm_source=rss&utm_medium=rss&utm_campaign=vogue-ukraine-presents-futurespective-an-exhibition-of-contemporary-ukrainian-photography-at-the-saatchi-gallery-in-london",
    highlight: false,
    sponsored: false,
  },
  {
    id: 17,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY & THE V&A PRESENT THE SECOND EDITION OF ACCLAIMED DUTCH FEMALE ARTISTS EXHIBITION, STANDING ON THE SHOULDERS OF GIANTS II: A UNIQUE DIALOGUE BETWEEN PAST AND PRESENT",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "From 22 November 2025, Saatchi Gallery will present the highly anticipated second edition of Standing on the Shoulders of Giants, featuring 10 contemporary Dutch female artists in collaboration with the V&#038;A. \n The post  SAATCHI GALLERY & THE V&A PRESENT THE SECOND EDITION OF ACCLAIMED DUTCH FEM",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-the-va-present-the-second-edition-of-acclaimed-dutch-female-artists-exhibition-standing-on-the-shoulders-of-giants-ii-a-unique-dialogue-between-past-and-present?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-the-va-present-the-second-edition-of-acclaimed-dutch-female-artists-exhibition-standing-on-the-shoulders-of-giants-ii-a-unique-dialogue-between-past-and-present",
    highlight: false,
    sponsored: false,
  },
  {
    id: 18,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "SAATCHI GALLERY TO PRESENT THE LONG NOW, AN EXHIBITION EXPLORING THEMES PREVALENT THROUGH 40 YEARS OF CONTEMPORARY ART",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Celebrating four decades of ground-breaking contemporary art, Saatchi Gallery will open landmark exhibition, The Long Now on 5 November 2025, supported by De Beers. This expansive group show will showcase new works by iconic artists closely associated with the Gallery\u2019s dynamic history, alongside fr",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-to-present-the-long-now-an-exhibition-exploring-themes-prevalant-through-40-years-of-contemporary-art?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-to-present-the-long-now-an-exhibition-exploring-themes-prevalant-through-40-years-of-contemporary-art",
    highlight: false,
    sponsored: false,
  },
  {
    id: 19,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "BAGRI FOUNDATION AND SAATCHI GALLERY PRESENT MYTHS, DREAMS AND NEW REALITIES, AN EXHIBITION PLATFORMING AN EMERGING GENERATION OF ASIAN ARTISTS",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Myths, Dreams and New Realities will spotlight 13 emerging artists from across the Asian diaspora, who each reimagine cultural identity through personal mythologies and visionary material practices.\u00a0Across the gallery space, dreamlike visuals unfurl as the artists investigate the entangled relations",
    url: "https://www.saatchigallery.com/press/release/bagri-foundation-and-saatchi-gallery-present-myths-dreams-and-new-realities-an-exhibition-platforming-an-emerging-generation-of-asian-artists?utm_source=rss&utm_medium=rss&utm_campaign=bagri-foundation-and-saatchi-gallery-present-myths-dreams-and-new-realities-an-exhibition-platforming-an-emerging-generation-of-asian-artists",
    highlight: false,
    sponsored: false,
  },
  {
    id: 20,
    type: "exhibition",
    category: "exhibition",
    label: "Exhibition",
    tag: "Exhibition",
    tagClass: "tag-exhibition",
    color: "#D4A020",
    title: "Saatchi Gallery presents HIP HOP \u2013 Living a Dream",
    artist: "",
    venue: "Saatchi Gallery",
    address: "Saatchi Gallery, London",
    neighbourhood: "central-london",
    lat: 51.4897, lng: -0.1594,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "Saatchi Gallery presents the photography of Jamel Shabazz, Joseph Rodriguez and Gregory Bojorquez in HIP HOP \u2013 Living a Dream, chronicling the rise and global impact of American Hip Hop culture. \n The post  Saatchi Gallery presents HIP HOP \u2013 Living a Dream  first appeared on  Saatchi Gallery .",
    url: "https://www.saatchigallery.com/press/release/saatchi-gallery-presents-hip-hop-living-a-dream?utm_source=rss&utm_medium=rss&utm_campaign=saatchi-gallery-presents-hip-hop-living-a-dream",
    highlight: false,
    sponsored: false,
  }
];

// ── TYPE CONFIG: colours, icons, labels ──
const EVENT_TYPES = {
  gallery:     { color: "#C8102E", icon: "🏛️", label: "Gallery Opening", markerColor: "#C8102E" },
  exhibition:  { color: "#D4A020", icon: "🖼️", label: "Exhibition",      markerColor: "#D4A020" },
  popup:       { color: "#1C6B3A", icon: "🛍️", label: "Pop-up & Market", markerColor: "#1C6B3A" },
  performance: { color: "#6B3FA0", icon: "🎭", label: "Performance",     markerColor: "#6B3FA0" },
  talk:        { color: "#2A5BAD", icon: "🎙️", label: "Artist Talk",     markerColor: "#2A5BAD" },
};
