// ─────────────────────────────────────────────────────────────────
//  Globe — Auto-generated Events Data
//  Last updated: 2026-06-28 08:16 UTC
//  Source: Eventbrite · Designmynight · Time Out · Resident Advisor
//  DO NOT EDIT MANUALLY — this file is overwritten daily
// ─────────────────────────────────────────────────────────────────

const GLOBE_EVENTS = [
  {
    id: 1,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "5 Things to spot in Paulo Nimer Pjota: Encantados",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  5 Things to spot in Paulo Nimer Pjota: Encantados  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/5-things-to-spot-in-paulo-nimer-pjota-encantados",
    highlight: false,
    sponsored: false,
  },
  {
    id: 2,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "New Limited Edition by Oscar Murillo with LITO",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  New Limited Edition by Oscar Murillo with LITO  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/new-limited-edition-by-oscar-murillo-with-lito",
    highlight: false,
    sponsored: false,
  },
  {
    id: 3,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Book recommendations from artist Ranti Bam",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Book recommendations from artist Ranti Bam  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/book-recommendations-from-artist-ranti-bam",
    highlight: false,
    sponsored: false,
  },
  {
    id: 4,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Ufuoma Essi from A Month of Single Frames to curate South by South film programme for 2026",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Ufuoma Essi from A Month of Single Frames to curate South by South film programme for 2026  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/ufuoma-essi-from-a-month-of-single-frames-to-curate-south-by-south-film-programme-for-2026",
    highlight: false,
    sponsored: false,
  },
  {
    id: 5,
    type: "performance",
    category: "performance",
    label: "Performance",
    tag: "Performance",
    tagClass: "tag-performance",
    color: "#6B3FA0",
    title: "Shortwave: A New Sound and Performance Festival",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Shortwave: A New Sound and Performance Festival  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/shortwave-a-new-sound-and-performance-festival",
    highlight: false,
    sponsored: false,
  },
  {
    id: 6,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Kat Anderson",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Kat Anderson  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-kat-anderson",
    highlight: false,
    sponsored: false,
  },
  {
    id: 7,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Manuel Hernandez Rivera",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Manuel Hernandez Rivera  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-manuel-hernandez-rivera",
    highlight: false,
    sponsored: false,
  },
  {
    id: 8,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Maya Silverberg",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Maya Silverberg  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-maya-silverberg",
    highlight: false,
    sponsored: false,
  },
  {
    id: 9,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "29 years later: Tracey Emin at the SLG",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  29 years later: Tracey Emin at the SLG  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/29-years-later-tracey-emin-at-the-slg",
    highlight: false,
    sponsored: false,
  },
  {
    id: 10,
    type: "gallery",
    category: "opening",
    label: "Gallery Opening",
    tag: "Gallery Opening",
    tagClass: "tag-opening",
    color: "#C8102E",
    title: "Interview with artist Samantha Fellows",
    artist: "",
    venue: "South London Gallery",
    address: "South London Gallery, London",
    neighbourhood: "southbank",
    lat: 51.471, lng: -0.0643,
    time: "See website",
    date: "On Now",
    price: "Free entry",
    priceDisplay: "Free entry",
    priceNum: 0,
    bookingType: "free",
    description: "The post  Interview with artist Samantha Fellows  appeared first on  South London Gallery .",
    url: "https://www.southlondongallery.org/journal/interview-with-artist-samantha-fellows",
    highlight: false,
    sponsored: false,
  }
];

// ── TYPE CONFIG: colours, icons, labels ──
const EVENT_TYPES = {
  gallery:     { color: "#C8102E", icon: "🏛️", label: "Gallery Opening", markerColor: "#C8102E" },
  exhibition:  { color: "#D4A020", icon: "🖼️", label: "Exhibition",      markerColor: "#D4A020" },
  popup:       { color: "#1C6B3A", icon: "🛍️", label: "Pop-up & Market", markerColor: "#1C6B3A" },
  performance: { color: "#6B3FA0", icon: "🎭", label: "Performance",     markerColor: "#6B3FA0" },
  talk:        { color: "#2A5BAD", icon: "🎙️", label: "Artist Talk",     markerColor: "#2A5BAD" },
};
